FROM eclipse-temurin:8u362-b09-jdk
SHELL ["/bin/bash", "-c"]
ENV PATH=$PATH:/usr/local/ssl/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/ssl/lib64:/usr/local/lib
ENV SSL_CERT_DIR=/etc/ssl/certs
RUN apt -y update && apt -y upgrade && apt -y install binutils gcc perl make zlib1g-dev g++
# openssl update
RUN cd /usr/local/src/  \
    && wget https://www.openssl.org/source/openssl-3.0.8.tar.gz  \
#    && apt -y purge openssl \
    && tar -xf openssl-3.0.8.tar.gz  \
    && cd openssl-3.0.8  \
    && ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib \
    && make && make install \
    && echo '/usr/local/ssl/lib64' > /etc/ld.so.conf.d/openssl-3.0.8.conf  \
#    && source /etc/ld.so.conf.d/openssl-3.0.8.conf \
    && ldconfig -v \
    && rm -f /usr/bin/c_rehash \
    && rm -f /usr/bin/openssl \
    && sed -i 's@.\{1\}$@:/usr/local/ssl/bin"@' /etc/environment \
    && cd .. \
    && rm -rf /usr/local/src/openssl-3.0.8 \
    && rm -f /usr/local/src/openssl-3.0.8.tar.gz
# curl update
RUN apt -y purge curl \
    && wget https://curl.se/download/curl-8.0.1.tar.gz  \
    && tar -xf curl-8.0.1.tar.gz  \
    && cd curl-8.0.1 \
    && CPPFLAGS="-I/usr/local/ssl/include" LDFLAGS="-L/usr/local/ssl/lib64" ./configure --with-openssl \
    && make && make install \
    && ldconfig -v \
    && cd ..  \
    && rm -f /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0 \
    && rm -rf curl-8.0.1 \
    && rm -f curl-8.0.1.tar.gz
# l4z update
RUN cd /usr/local/src/  \
    && wget https://github.com/lz4/lz4/archive/refs/tags/v1.9.4.tar.gz \
    && tar -xf v1.9.4.tar.gz \
    && cd lz4-1.9.4 \
    && make && make install \
    && ldconfig -v \
    && rm -f ./usr/lib/x86_64-linux-gnu/liblz4.so.1.9.3 \
    && cd ..  \
    && rm -rf /usr/local/src/lz4-1.9.4 \
    && rm -f /usr/local/src/v1.9.4.tar.gz
# free type update
RUN cd /usr/local/src/  \
    && wget https://download.savannah.gnu.org/releases/freetype/freetype-2.13.0.tar.gz \
    && tar -xf freetype-2.13.0.tar.gz \
    && cd freetype-2.13.0 \
    && make && make install \
    && apt -y purge libfreetype6 \
    && ldconfig -v \
    && rm -f /usr/lib/x86_64-linux-gnu/libfreetype.so.6.18.1 \
    && rm -f /usr/lib/x86_64-linux-gnu/libfreetype.so.6 \
    && cd ..  \
    && rm -rf /usr/local/src/freetype-2.13.0 \
    && rm -f /usr/local/src/freetype-2.13.0.tar.gz
# pcre2 update
COPY pcre-8.45.tar.gz /usr/local/src/pcre-8.45.tar.gz
RUN cd /usr/local/src/  \
    && tar -xf pcre-8.45.tar.gz \
    && cd pcre-8.45 \
    && ./configure \
    && make && make install \
    && ln -s /usr/local/lib/libpcre.so.1.2.13 /usr/local/lib/libpcre.so.3 \
    && ln -s /usr/local/lib/libpcreposix.so.0.0.7 /usr/local/lib/libpcreposix.so.3 \
    && rm -f /usr/lib/x86_64-linux-gnu/libpcre.so.3 \
    && rm -f /usr/lib/x86_64-linux-gnu/libpcre.so.3.13.3 \
    && rm -f /usr/lib/x86_64-linux-gnu/libpcreposix.so.3 \
    && rm -f /usr/lib/x86_64-linux-gnu/libpcreposix.so.3.13.3 \
    && rm -f /var/lib/dpkg/info/libpcre3:amd64.md5sums \
    && rm -f /var/lib/dpkg/info/libpcre3:amd64.symbols \
    && rm -f /var/lib/dpkg/info/libpcre3:amd64.shlibs \
    && rm -f /var/lib/dpkg/info/libpcre3:amd64.triggers \
    && rm -f /var/lib/dpkg/info/libpcre3:amd64.list \
    && rm -rf /usr/local/share/doc/pcre \
    && rm -rf /usr/share/doc/libpcre3 \
    && ldconfig -v \
    && cd ..  \
    && rm -rf /usr/local/src/pcre-8.45 \
    && rm -f /usr/local/src/pcre-8.45.tar.gz
# linux-pam premove
RUN rm -rf /usr/share/pam
RUN apt -y purge binutils && apt -y purge gcc && apt -y purge perl && apt -y purge make && apt -y purge zlib1g-dev && apt -y purge g++ && apt -y autoremove