FROM amazoncorretto:8-alpine3.14

RUN apk add --no-cache wget
RUN apk add --no-cache bash
RUN apk add --no-cache libnsl
RUN apk add --update libaio libnsl && ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1a